Fixed Latex Makefile bug

diff --git a/latex_templates/Makefile b/latex_templates/Makefile
--- a/latex_templates/Makefile
+++ b/latex_templates/Makefile
@@ -1,22 +1,13 @@
 TEX=pdflatex
 OUTPUT_DIR=../media/generated_pdfs
 
-all: thesis withdrawal
-
-# Generate thesis PDF only if the corresponding .tex file exists
-thesis:
-	@if ls thesis_filled_*.tex 1> /dev/null 2>&1; then \
-		$(TEX) -output-directory=$(OUTPUT_DIR) thesis_filled_*.tex; \
+all:
+	@if [ -z "$(file)" ]; then \
+		echo "Error: file variable is not set"; \
+		exit 1; \
 	else \
-		echo "No thesis form to process."; \
-	fi
-
-# Generate withdrawal PDF only if the corresponding .tex file exists
-withdrawal:
-	@if ls withdrawal_filled_*.tex 1> /dev/null 2>&1; then \
-		$(TEX) -output-directory=$(OUTPUT_DIR) withdrawal_filled_*.tex; \
-	else \
-		echo "No withdrawal form to process."; \
+		echo "Compiling $(file) into $(OUTPUT_DIR)"; \
+		$(TEX) -output-directory=$(OUTPUT_DIR) $(file); \
 	fi
 
 clean:
